name: SafeCreeper
description: 'Get full control of creatures, players and almost everything!'
main: com.timvisee.safecreeper.SafeCreeper
version: 1.3.1
load: startup
author: timvisee
website: http://timvisee.com/
softdepend: [Vault] #hack to fix trove errors
commands:
  safecreeper:
    description: Safe Creeper command
    usage: /safecreeper <values>
  sc:
    description: Safe Creeper command
    usage: /sc <values>