# Config file

# Set if the permissions system is enabled
usePermissions: true

# Set if bypass permissions are enabled. usePermissions has to be enabled.
useBypassPermissions: false

# Set if the update checker is enabled.
enableUpdateCheckerOnStartup: true

# Set if a message is send to players with permission when they join if there's an update available.
sendMessageWhenUpdateAvailable: true

# This are the file/folder paths where files are saved
GlobalConfigFilePath: 'plugins/SafeCreeper/global.yml'
WorldConfigsFolderPath: 'plugins/SafeCreeper/worlds'